services:
  publisher:
    build: ./publisher
    container_name: zmq_publisher
    ports:
      - "8080:8080"

  subscriber:
    build: ./subscriber
    container_name: zmq_subscriber
    depends_on:
      - publisher